"""
Excel Report Generator
----------------------
Turns the tracker's CSV output into a polished, client-ready Excel report:

  Sheet 1  Summary        - key numbers (live formulas, recalculates in Excel)
  Sheet 2  Products       - full formatted product table with autofilter
  Sheet 3  Price Changes  - what got more expensive / cheaper since last run

Usage:
    python report.py                     # reads ./data, writes ./data/price_report.xlsx
    python report.py --data-dir mydata   # custom folder

Author: <your name> | github.com/<your-username>
"""

import argparse
import csv
import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from tracker import detect_changes

# ---------- shared styles ----------
FONT_NAME = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="1F4E5F")
HEADER_FONT = Font(name=FONT_NAME, bold=True, color="FFFFFF", size=11)
BODY_FONT = Font(name=FONT_NAME, size=10)
TITLE_FONT = Font(name=FONT_NAME, bold=True, size=14, color="1F4E5F")
THIN = Side(style="thin", color="B0B0B0")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
PRICE_FMT = '"£"#,##0.00'
UP_FONT = Font(name=FONT_NAME, size=10, color="C00000", bold=True)     # price increased
DOWN_FONT = Font(name=FONT_NAME, size=10, color="007A33", bold=True)   # price dropped


def style_header_row(ws, row: int, n_cols: int) -> None:
    for col in range(1, n_cols + 1):
        cell = ws.cell(row=row, column=col)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.border = BORDER
        cell.alignment = Alignment(horizontal="center", vertical="center")


def autofit(ws, widths: dict[int, int]) -> None:
    for col, width in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = width


def read_csv(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def build_products_sheet(wb: Workbook, products: list[dict]) -> None:
    ws = wb.create_sheet("Products")
    headers = ["Title", "Price", "Rating (1-5)", "Stock", "Product URL"]
    ws.append(headers)
    style_header_row(ws, 1, len(headers))

    for p in products:
        ws.append([p["title"], float(p["price"]), int(p["rating"]), p["stock"], p["url"]])

    for row in ws.iter_rows(min_row=2, max_row=ws.max_row, max_col=5):
        for cell in row:
            cell.font = BODY_FONT
            cell.border = BORDER
        row[1].number_format = PRICE_FMT
        row[2].alignment = Alignment(horizontal="center")
        row[3].alignment = Alignment(horizontal="center")

    autofit(ws, {1: 46, 2: 12, 3: 13, 4: 14, 5: 52})
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:E{ws.max_row}"


def build_changes_sheet(wb: Workbook, changes: list[dict]) -> None:
    ws = wb.create_sheet("Price Changes")
    headers = ["Title", "Old Price", "New Price", "Change", "Change %"]
    ws.append(headers)
    style_header_row(ws, 1, len(headers))

    if not changes:
        ws.append(["No price changes detected between the last two runs.", "", "", "", ""])
        ws.cell(row=2, column=1).font = BODY_FONT
    else:
        for c in changes:
            ws.append([c["title"], c["old_price"], c["new_price"], c["change"], c["change_pct"] / 100])
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row, max_col=5):
            direction = UP_FONT if (row[3].value or 0) > 0 else DOWN_FONT
            for cell in row:
                cell.font = BODY_FONT
                cell.border = BORDER
            row[1].number_format = PRICE_FMT
            row[2].number_format = PRICE_FMT
            row[3].number_format = PRICE_FMT
            row[3].font = direction
            row[4].number_format = "+0.0%;-0.0%"
            row[4].font = direction

    autofit(ws, {1: 46, 2: 12, 3: 12, 4: 12, 5: 12})
    ws.freeze_panes = "A2"


def build_summary_sheet(wb: Workbook, n_changes: int) -> None:
    """Summary uses live Excel formulas, so the report recalculates if data is edited."""
    ws = wb.create_sheet("Summary", 0)  # first tab
    ws["A1"] = "Price Tracking Report"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = "Generated by an automated Python scraper - github.com/<your-username>"
    ws["A2"].font = Font(name=FONT_NAME, size=9, italic=True, color="808080")

    rows = [
        ("Total products tracked", "=COUNTA(Products!A:A)-1"),
        ("Average price", "=AVERAGE(Products!B:B)"),
        ("Highest price", "=MAX(Products!B:B)"),
        ("Lowest price", "=MIN(Products!B:B)"),
        ("Products in stock", '=COUNTIF(Products!D:D,"In stock")'),
        ("Products out of stock", '=COUNTIF(Products!D:D,"Out of stock")'),
        ("Price changes since last run", n_changes),
    ]
    start = 4
    for i, (label, value) in enumerate(rows):
        r = start + i
        ws.cell(row=r, column=1, value=label).font = Font(name=FONT_NAME, size=10, bold=True)
        vcell = ws.cell(row=r, column=2, value=value)
        vcell.font = BODY_FONT
        if "price" in label.lower() and "changes" not in label.lower():
            vcell.number_format = PRICE_FMT
        ws.cell(row=r, column=1).border = BORDER
        vcell.border = BORDER

    autofit(ws, {1: 32, 2: 16})


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Excel report from tracker data")
    parser.add_argument("--data-dir", default="data", help="folder containing the tracker CSVs")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    latest = data_dir / "products_latest.csv"
    history = data_dir / "price_history.csv"

    if not latest.exists():
        print(f"'{latest}' not found. Run tracker.py first.")
        return 1

    products = read_csv(latest)
    changes = detect_changes(history)

    wb = Workbook()
    wb.remove(wb.active)  # drop the default empty sheet
    build_products_sheet(wb, products)
    build_changes_sheet(wb, changes)
    build_summary_sheet(wb, len(changes))

    out_path = data_dir / "price_report.xlsx"
    wb.save(out_path)
    print(f"Report written: {out_path}")
    print(f"  Products: {len(products)} | Price changes: {len(changes)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
